### ISSUE TITLE
NodeJS 15 EventTarget fail

### ISSUE THREAD

**Issue by WebReflection** [WebReflection/heresy-ssr#25]
I have no idea what's going on NodeJS 15 so I need to investigate this one.

```
TypeError: Cannot set property target of #<Event> which has only a getter
    at Object.dispatchEvent (/home/ag/git/heresy-ssr/node_modules/basichtml/src/EventTarget.js:66:37)
    at Object.init (/home/ag/git/heresy-ssr/node_modules/heresy/cjs/augmented.js:320:10)
    at Object.value (/home/ag/git/heresy-ssr/node_modules/heresy/cjs/augmented.js:171:22)
    at Object.connect (/home/ag/git/heresy-ssr/node_modules/basichtml/src/utils.js:25:11)
    at resetParent (/home/ag/git/heresy-ssr/node_modules/basichtml/src/Node.js:17:11)
    at HTMLTemplateElement.appendChild (/home/ag/git/heresy-ssr/node_modules/basichtml/src/Node.js:46:18)
    at Object.onclosetag (/home/ag/git/heresy-ssr/node_modules/basichtml/src/Element.js:55:27)
    at Parser.onclosetag (/home/ag/git/heresy-ssr/node_modules/htmlparser2/lib/Parser.js:231:35)
    at Tokenizer._emitToken (/home/ag/git/heresy-ssr/node_modules/htmlparser2/lib/Tokenizer.js:846:24)
    at Tokenizer._stateInClosingTagName (/home/ag/git/heresy-ssr/node_modules/htmlparser2/lib/Tokenizer.js:187:18)
```

**Comment by WebReflection** [comment]
actually, it was `Event` due the fact NodeJS implements native *Event* and *EventTarget* interfaces.

Fixed via *basicHTML*.
